### ISSUE TITLE
Internal hyperlinks when loading HTML from assets

### ISSUE THREAD

**Issue by FriedrichFroebel** [stefanhaustein/nativehtml#16]
I tried to add internal hyperlinks (anchors) to my HTML file stored in the assets folder, but it keeps failing with an exception:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=file:/android_asset/html/index.html }
                      at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1545)
                      at android.app.Instrumentation.execStartActivity(Instrumentation.java:1416)
                      at android.app.Activity.startActivityForResult(Activity.java:3351)
                      at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                      at android.app.Activity.startActivityForResult(Activity.java:3312)
                      at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:720)
                      at android.app.Activity.startActivity(Activity.java:3522)
                      at android.app.Activity.startActivity(Activity.java:3490)
                      at org.kobjects.nativehtml.android.AndroidPlatform.openInBrowser(AndroidPlatform.java:61)
                      at org.kobjects.nativehtml.io.DefaultRequestHandler.openLink(DefaultRequestHandler.java:36)
                      at org.kobjects.nativehtml.android.AndroidTextComponent$1.onClick(AndroidTextComponent.java:297)
                      at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:212)
                      at android.widget.TextView.onTouchEvent(TextView.java:7383)
                      at android.view.View.dispatchTouchEvent(View.java:7127)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2176)
                      at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1919)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1925)
                      at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1379)
                      at android.app.Activity.dispatchTouchEvent(Activity.java:2396)
                      at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1873)
                      at android.view.View.dispatchPointerEvent(View.java:7307)
                      at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3174)
                      at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3119)
                      at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4155)
                      at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4134)
                      at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4226)
                      at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
                      at android.os.MessageQueue.nativePollOnce(Native Method)
                     at android.os.MessageQueue.next(MessageQueue
```

My HTML file:

```html
<html>
<body>
<p><a href="#test">Link to test</a></p>
<p id="test">A simple test text</p>
</body>
</html>
```

My Activity code:

```java
package test;

import org.kobjects.nativehtml.android.HtmlView;
import java.io.*;
import java.net.*;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ScrollView;

public class MyActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_my);

        final ScrollView scrollView = findViewById(R.id.scrollView);
        final HtmlView htmlView = new HtmlView(this);

        try {
            final Reader reader = new BufferedReader(new InputStreamReader(getAssets().open("html/index.html"), "UTF-8"));
            final URI uri = new URI("file:///android_asset/html/index.html");
            final int lastIndex = uri.toString().lastIndexOf("/");
            final String prefix = uri.toString().substring(0, lastIndex + 1);
            htmlView.addInternalLinkPrefix(prefix);
            htmlView.loadHtml(reader, uri);
        } catch (IOException | URISyntaxException exception) {
            super.onBackPressed();
            return;
        }

        scrollView.addView(htmlView);
    }
}
```

**Comment by stefanhaustein** [comment]
URL syntax for assets should probably be ``file:///android_asset/``

**Comment by FriedrichFroebel** [comment]
This raises the same exception.

**Comment by stefanhaustein** [comment]
Probably an issue with internal link prefix matching, will take a look later today...

**Comment by stefanhaustein** [comment]
I have found a problem with fragment handling in resolveUrl, but I that does not seem to explain the issue you are seeing: https://github.com/stefanhaustein/nativehtml/commit/b85ff58f33533c43d3790fdae2986784d6853847

If you print the prefix, is it ``file:///android_asset/html/`` or just ``file:/android_asset/html/``?  In the stack trace, ``file:/android_asset/html/index.html`` looks suspicious because it's different from the string supplied to the URI constructor in your setup code. 

Have you tried absolute URLs that start with the prefix? For some reason, the resolved URL does not seem to match the prefix.

**Comment by FriedrichFroebel** [comment]
Prefix has the value `file:///android_asset/html/`.

What do you mean by absolute URLs? Using `<a href="file:///android_asset/html/index.html#test">` for example causes an 

> java.io.FileNotFoundException: /android_asset/html/index.html: open failed: ENOENT (No such file or directory)

 exception.

**Comment by stefanhaustein** [comment]
Can you manually add ``file:/android_asset/html`` (only one slash) as a prefix, as this is the prefix shown in the exception?

**Comment by FriedrichFroebel** [comment]
This raises the same `FileNotFoundException` as in my last comment.

**Comment by stefanhaustein** [comment]
Ok, the io exception means we are one step further: the prefix is recognized and the component tries to load a file. So I still need to add some special handling for asset paths.. 

p.s. Where did you find the "assets" url syntax from the original bug report? Is that something that should be working on Android? The file:///android_assets seems to be specific to the web view, but it should be relatively straightforward to emulate it....

**Comment by stefanhaustein** [comment]
Update:
I have added an AndroidDefaultRequestHandler that should be able to properly handle urls starting with ``file:///android_asset/``

**Comment by FriedrichFroebel** [comment]
Seems like their still is an error when trying to resolve as the anchor is added to the filename:

```
java.lang.RuntimeException: java.io.FileNotFoundException: html/index.html#test
    at org.kobjects.nativehtml.android.AndroidDefaultRequestHandler.openInternalLink(AndroidDefaultRequestHandler.java:32)
    at org.kobjects.nativehtml.io.DefaultRequestHandler.openLink(DefaultRequestHandler.java:31)
    at org.kobjects.nativehtml.android.AndroidTextComponent$1.onClick(AndroidTextComponent.java:297)
...
```

**Comment by stefanhaustein** [comment]
Thanks! Just realized that resource loading will be a problem, too. So I'll also add openInputStream(url) to platform and remove the AndroidDefaultRequestHandler later today.

**Comment by stefanhaustein** [comment]
Should be fixed now O:)

**Comment by FriedrichFroebel** [comment]
It is still throwing an error:

```
java.lang.RuntimeException: java.io.FileNotFoundException: index.html
    at org.kobjects.nativehtml.io.DefaultRequestHandler.openInternalLink(DefaultRequestHandler.java:44)
    at org.kobjects.nativehtml.io.DefaultRequestHandler.openLink(DefaultRequestHandler.java:31)
    at org.kobjects.nativehtml.android.AndroidTextComponent$1.onClick(AndroidTextComponent.java:297)
...
```

**Comment by stefanhaustein** [comment]
Hm, now the html folder seems to be missing. Probably did something wrong
when adjusting the cut position calculation for the fragment... :-/

**Comment by stefanhaustein** [comment]
https://github.com/stefanhaustein/nativehtml/commit/034c89700c15d6a50b950c5ba76460d0ca332dab

**Comment by FriedrichFroebel** [comment]
Now it does not throw an error anymore, but seems like it always jumps to the top of the file after loading (and not to the anchor of the hyperref target).

**Comment by stefanhaustein** [comment]
Would you mind filing a new FR and closing this bug? I doubt this works for any type of URL currently.
