### ISSUE TITLE
crash on html acid test rendring

### ISSUE THREAD

**Issue by 0x410c** [stefanhaustein/nativehtml#2]
this is the html css acid test code

```
<html>
<head>
    <title>
        display/box/float/clear test
    </title>
    <style type="text/css">
/* last modified: 1 Dec 98 */

html {
font: 10px/1 Verdana, sans-serif;
background-color: blue;
color: white;
}

body {
margin: 1.5em;
border: .5em solid black;
padding: 0;
width: 48em;
background-color: white;
}

dl {
margin: 0;
border: 0;
padding: .5em;
}

dt {
background-color: rgb(204,0,0);
margin: 0;
padding: 1em;
width: 10.638%; /* refers to parent element's width of 47em. = 5em or 50px */
height: 28em;
border: .5em solid black;
float: left;
}

dd {
float: right;
margin: 0 0 0 1em;
border: 1em solid black;
padding: 1em;
width: 34em;
height: 27em;
}

ul {
margin: 0;
border: 0;
padding: 0;
}

li {
display: block; /* i.e., suppress marker */
color: black;
height: 9em;
width: 5em;
margin: 0;
border: .5em solid black;
padding: 1em;
float: left;
background-color: #FC0;
}

#bar {
background-color: black;
color: white;
width: 41.17%; /* = 14em */
border: 0;
margin: 0 1em;
}

#baz {
margin: 1em 0;
border: 0;
padding: 1em;
width: 10em;
height: 10em;
background-color: black;
color: white;
}

form {
margin: 0;
display: inline;
}

p {
margin: 0;
}

form p {
line-height: 1.9;
}

blockquote {
margin: 1em 1em 1em 2em;
border-width: 1em 1.5em 2em .5em;
border-style: solid;
border-color: black;
padding: 1em 0;
width: 5em;
height: 9em;
float: left;
background-color: #FC0;
color: black;
}

address {
font-style: normal;
}

h1 {
background-color: black;
color: white;
float: left;
margin: 1em 0;
border: 0;
padding: 1em;
width: 10em;
height: 10em;
font-weight: normal;
font-size: 1em;
}
  </style>
</head>
<body>
<dl>
    <dt>
        toggle
    </dt>
    <dd>
        <ul>
            <li>
                the way
            </li>
            <li id="bar">
                <p>
                    the world ends
                </p>
                <form action="./" method="get">
                    <p>
                        bang
                        <input type="radio" name="foo" value="off">
                    </p>
                    <p>
                        whimper
                        <input type="radio" name="foo2" value="on">
                    </p>
                </form>
            </li>
            <li>
                i grow old
            </li>
            <li id="baz">
                pluot?
            </li>
        </ul>
        <blockquote>
            <address>
                bar maids,
            </address>
        </blockquote>
        <h1>
            sing to me, erbarme dich
        </h1>
    </dd>
</dl>
<p style="color: black; font-size: 1em; line-height: 1.3em; clear: both">
    This is a nonsensical document, but syntactically valid HTML 4.0. All 100%-conformant CSS1 agents should be able to render the document elements above this paragraph indistinguishably (to the pixel) from this
    <a href="sec5526c.gif">reference rendering,</a>
    (except font rasterization and form widgets). All discrepancies should be traceable to CSS1 implementation shortcomings. Once you have finished evaluating this test, you can return to the <A HREF="sec5526c.htm">parent page</A>.
</p>
</body>
</html>
```

Rendering this gives a crash :
```

FATAL EXCEPTION: main
Process: org.kobjects.nativehtml.demo.android, PID: 10735
java.lang.NullPointerException: Attempt to invoke virtual method 'float org.kobjects.nativehtml.css.CssStyleDeclaration.getPx(org.kobjects.nativehtml.css.CssProperty, float)' on a null object reference
    at org.kobjects.nativehtml.android.AndroidWrapperElement.onLayout(AndroidWrapperElement.java:28)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at org.kobjects.nativehtml.android.AndroidContainerElement.onLayout(AndroidContainerElement.java:57)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.widget.ScrollView.onLayout(ScrollView.java:1535)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
    at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
    at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
    at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
    at android.view.View.layout(View.java:17637)
    at android.view.ViewGroup.layout(ViewGroup.java:5575)
    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
    at android.view.Choreographer.doCallbacks(Choreographer.java:686)
    at android.view.Choreographer.doFrame(Choreographer.java:621)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
```

**Comment by 0x410c** [comment]
for reference check these tests
http://www.acidtests.org/

**Comment by stefanhaustein** [comment]
Looks like the same NPE as for the input link... Does the problem persist?

**Comment by 0x410c** [comment]
crash is fixed on acid 1 test, but still crashing on acid2 test, plus acid 1 test is not rendered correctly.

**Comment by stefanhaustein** [comment]
It looks like the crash is caused by some kind of problem of the xml parser baked into android with the doctype declaration -- it doesn't seem to crash if I remove the doctype declaration from the html. Not sure about the best way to fix this yet (force inclusion of a more recent kxml or do some preprocessing).

Concerning acid1 rendering: floats are not supported.

The acid tests in general don't seem to be very helpful where only a subset of CSS is supported: The rendered output will look wrong wrt to the reference image, and it's hard to tell to which extent this is due to unsupported features vs. bugs in features that should be supported.

**Comment by 0x410c** [comment]
why not create a document giving reference, which properties attributes are supported for both html and css.
secondly i am very much interested in further developing it to support full fledged html and css renderer. i have plans.

do give your opinion

**Comment by stefanhaustein** [comment]
I have extended the readme accordingly. The only CSS 2 limitation should really be that floats are not supported, but there might still be bugs. For the use cases I imagine, I think it would be more important to add support for some CSS3 features (such as flexbox) than putting efforts into legacy features such as floats to make ACID happy...
