### ISSUE TITLE
Can't use HtmlView in Layout?

### ISSUE THREAD

**Issue by nilskretschmer** [stefanhaustein/nativehtml#27]
It seems to be impossible to use HtmlView in a layout ressource file, because inflating always fails like this:
`                   Caused by: android.view.InflateException: Binary XML file line #53: Binary XML file line #1: Binary XML file line #1: Error inflating class org.kobjects.nativehtml.android.HtmlView
                   Caused by: android.view.InflateException: Binary XML file line #1: Binary XML file line #1: Error inflating class org.kobjects.nativehtml.android.HtmlView
                   Caused by: android.view.InflateException: Binary XML file line #1: Error inflating class org.kobjects.nativehtml.android.HtmlView
                   Caused by: java.lang.NoSuchMethodException: <init> [class android.content.Context, interface android.util.AttributeSet]`

I tried it by using a Fragment (and a fragment's layout file) and in a normal activity layout. It always crashes with that error.

**Comment by stefanhaustein** [comment]
It should be straightforward to add the missing constructor for instantiation from XML... What does your use case look like -- do you have a URL or HTML content that you'd like to provide in the XML file (I don't think it would be feasible to embed unescaped HTML there)

**Comment by nilskretschmer** [comment]
I am a bit confused, because I tried exactly that by adding the library to my dependencies and editing it. But there already seems to be a constructor for that. I can confirm this by looking at the code here on GitHub:

    public HtmlView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init(context);
    }
Edit: Adding the HtmlView into an existing View programmatically is no problem. For example:

        LinearLayout linearLayoutUndone = findViewById(R.id.checkedtodolayout);
        htmlViewUndone = new HtmlView(this);
        linearLayoutUndone.addView(htmlViewUndone, 0);

Works fine. But if I insert a HtmlView add that position in my XML layout, the error is thrown.-

**Comment by stefanhaustein** [comment]
The readme was pointing to an old release (1.0.2 instead of 1.0.6, should be fixed now), perhaps this is the problem?

**Comment by nilskretschmer** [comment]
Ah well this seems to fix it. I upgraded to 1.0.6 now. No inflateException anymore. But now I get an error when loading the html:

        String html = "<input type=\"checkbox\">test text";
        String filename = "test.html";
        FileOutputStream outputStream;


        try {
            outputStream = openFileOutput(filename, Context.MODE_PRIVATE);
            outputStream.write(html.getBytes());
            outputStream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

            indexUrl = getFileStreamPath("test.html").toURI();
            String prefix = indexUrl.toString();
            int cut = prefix.lastIndexOf('/');
            prefix = prefix.substring(0, cut + 1);
            htmlViewUndone.addInternalLinkPrefix(prefix);

            htmlViewUndone.loadHtml(indexUrl);

I didn't change this code but now I got this:
`Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: 0/de.rememberly.rememberlyandroidapp/files/test.html`

The file is present in this directory (shown in device file manager):
data/data/<appname>/files/test.html

This code worked just fine before the upgrade and by using the addView method.. I was able to confirm this behaviour by downgrading to 1.0.2 - everything works here (but with the error not being able to add htmlview to layout xml)

**Comment by stefanhaustein** [comment]
Strange... Do you have a full stack trace? What is the value of indexUrl?

**Comment by nilskretschmer** [comment]
I tested it with the same code (no layout inflating, just adding the HtmlView).
This is the Full Stack Trace (version 1.0.6):

`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: de.rememberly.rememberlyandroidapp, PID: 21400
                  java.lang.RuntimeException: Unable to start activity ComponentInfo{de.rememberly.rememberlyandroidapp/de.rememberly.rememberlyandroidapp.activities.RenderActivity}: java.lang.RuntimeException: java.io.FileNotFoundException: 0/de.rememberly.rememberlyandroidapp/files/test.html
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6626)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
                   Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: 0/de.rememberly.rememberlyandroidapp/files/test.html
                      at org.kobjects.nativehtml.io.DefaultRequestHandler.openInternalLink(DefaultRequestHandler.java:44)
                      at org.kobjects.nativehtml.android.HtmlView.loadHtml(HtmlView.java:46)
                      at de.rememberly.rememberlyandroidapp.activities.RenderActivity.onCreate(RenderActivity.java:73)
                      at android.app.Activity.performCreate(Activity.java:7032)
                      at android.app.Activity.performCreate(Activity.java:7023)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6626) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
                   Caused by: java.io.FileNotFoundException: 0/de.rememberly.rememberlyandroidapp/files/test.html
                      at android.content.res.AssetManager.openAsset(Native Method)
                      at android.content.res.AssetManager.open(AssetManager.java:374)
                      at android.content.res.AssetManager.open(AssetManager.java:348)
                      at org.kobjects.nativehtml.android.AndroidPlatform.openInputStream(AndroidPlatform.java:70)
                      at org.kobjects.nativehtml.io.DefaultRequestHandler.openInternalLink(DefaultRequestHandler.java:42)
                      at org.kobjects.nativehtml.android.HtmlView.loadHtml(HtmlView.java:46) 
                      at de.rememberly.rememberlyandroidapp.activities.RenderActivity.onCreate(RenderActivity.java:73) 
                      at android.app.Activity.performCreate(Activity.java:7032) 
                      at android.app.Activity.performCreate(Activity.java:7023) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1236) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2814) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2943) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1630) 
                      at android.os.Handler.dispatchMessage(Handler.java:106) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6626) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
`

The value of indexUrl is: `file:/data/user/0/de.rememberly.rememberlyandroidapp/files/test.html`. This is exactly the same in version 1.0.2 and 1.0.6.

This is the SourceCode (I didn't change this SourceCode between the tested versions):

        LinearLayout linearLayoutUndone = findViewById(R.id.checkedtodolayout);
        htmlViewUndone = new HtmlView(this);
        linearLayoutUndone.addView(htmlViewUndone, 0);

        String html = "<input type=\"checkbox\">test text";
        String filename = "test.html";
        FileOutputStream outputStream;


        try {
            outputStream = openFileOutput(filename, Context.MODE_PRIVATE);
            outputStream.write(html.getBytes());
            outputStream.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

            indexUrl = getFileStreamPath("test.html").toURI();
            Log.i("URI: ", indexUrl.toString());
            String prefix = indexUrl.toString();
            int cut = prefix.lastIndexOf('/');
            prefix = prefix.substring(0, cut + 1);
            htmlViewUndone.addInternalLinkPrefix(prefix);

            htmlViewUndone.loadHtml(indexUrl);

The error only appears if I change to 1.0.6. The code is untouched. If I use 1.0.2 everything works fine.

**Comment by stefanhaustein** [comment]
Did you check if the resolved files match exactly and the file permission wasn't removed in the mainfest in the meantime? I can't easily repro for a few days O:)

**Comment by nilskretschmer** [comment]
The log resolves to the same file in both versions:
1.0.2:
`I/URI:: file:/data/user/0/de.rememberly.rememberlyandroidapp/files/test.html`
1.0.6:
`I/URI:: file:/data/user/0/de.rememberly.rememberlyandroidapp/files/test.html`

I doublechecked this. In addition I write and read to/from the internal storage - there is no need for permissions to write or read from the html..

But when I use the exact same code with 1.0.6 I get the Error Stack shown above..
I really don't know what's going on here..

EDIT:
I also tested to delete the file and rewrite it - it works fine. So the error only appears in 1.0.6 in the loadHtml method..

**Comment by stefanhaustein** [comment]
Would you mind checking the intermediate versions so we know at which transition it broke? I was using a "free for OS development" version of IntelliJ and the license ran out and now I am a bit disorganized still with my setup....

**Comment by nilskretschmer** [comment]
I checked all the versions. The FileNotFoundException happens with 1.0.5 and 1.0.6 - so 1.0.5 seems to break the loadHtml method if loaded from local (internal) file - If I load something via URL from the web there seems to be no error.
